{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Response exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 2.1.1
- `protoc` 3.19.4
- the following specification file: `response.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.1.0) version latest or higher.


-}

import Maybe
import Protobuf.Decode
import Protobuf.Encode


{-| Default for QueueForm. Should only be used for 'required' decoders as an initial value.


-}
defaultQueueForm : QueueForm
defaultQueueForm =
    { domain = "", timestamp = "", restoreId = "", email = "", action = "", method = "" }


{-| Decode a `QueueForm` from Bytes


-}
decodeQueueForm : Protobuf.Decode.Decoder QueueForm
decodeQueueForm =
    Protobuf.Decode.message
        defaultQueueForm
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | domain = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | timestamp = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | restoreId = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | email = a })
        , Protobuf.Decode.optional 5 Protobuf.Decode.string (\a r -> { r | action = a })
        , Protobuf.Decode.optional 6 Protobuf.Decode.string (\a r -> { r | method = a })
        ]


{-| Encode a `QueueForm` to Bytes


-}
encodeQueueForm : QueueForm -> Protobuf.Encode.Encoder
encodeQueueForm value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.domain )
        , ( 2, Protobuf.Encode.string value.timestamp )
        , ( 3, Protobuf.Encode.string value.restoreId )
        , ( 4, Protobuf.Encode.string value.email )
        , ( 5, Protobuf.Encode.string value.action )
        , ( 6, Protobuf.Encode.string value.method )
        ]


{-| `QueueForm` message


-}
type alias QueueForm =
    { domain : String, timestamp : String, restoreId : String, email : String, action : String, method : String }


{-| Default for ConfirmSignupForm. Should only be used for 'required' decoders as an initial value.


-}
defaultConfirmSignupForm : ConfirmSignupForm
defaultConfirmSignupForm =
    { username = "", code = "" }


{-| Decode a `ConfirmSignupForm` from Bytes


-}
decodeConfirmSignupForm : Protobuf.Decode.Decoder ConfirmSignupForm
decodeConfirmSignupForm =
    Protobuf.Decode.message
        defaultConfirmSignupForm
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | username = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | code = a })
        ]


{-| Encode a `ConfirmSignupForm` to Bytes


-}
encodeConfirmSignupForm : ConfirmSignupForm -> Protobuf.Encode.Encoder
encodeConfirmSignupForm value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.username )
        , ( 2, Protobuf.Encode.string value.code )
        ]


{-| `ConfirmSignupForm` message


-}
type alias ConfirmSignupForm =
    { username : String, code : String }


{-| Default for SignupForm. Should only be used for 'required' decoders as an initial value.


-}
defaultSignupForm : SignupForm
defaultSignupForm =
    { username = "", password = "", email = "", recaptcha = "" }


{-| Decode a `SignupForm` from Bytes


-}
decodeSignupForm : Protobuf.Decode.Decoder SignupForm
decodeSignupForm =
    Protobuf.Decode.message
        defaultSignupForm
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | username = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | password = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | email = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | recaptcha = a })
        ]


{-| Encode a `SignupForm` to Bytes


-}
encodeSignupForm : SignupForm -> Protobuf.Encode.Encoder
encodeSignupForm value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.username )
        , ( 2, Protobuf.Encode.string value.password )
        , ( 3, Protobuf.Encode.string value.email )
        , ( 4, Protobuf.Encode.string value.recaptcha )
        ]


{-| `SignupForm` message


-}
type alias SignupForm =
    { username : String, password : String, email : String, recaptcha : String }


{-| Default for LoginForm. Should only be used for 'required' decoders as an initial value.


-}
defaultLoginForm : LoginForm
defaultLoginForm =
    { username = "", password = "", recaptcha = "" }


{-| Decode a `LoginForm` from Bytes


-}
decodeLoginForm : Protobuf.Decode.Decoder LoginForm
decodeLoginForm =
    Protobuf.Decode.message
        defaultLoginForm
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | username = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | password = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | recaptcha = a })
        ]


{-| Encode a `LoginForm` to Bytes


-}
encodeLoginForm : LoginForm -> Protobuf.Encode.Encoder
encodeLoginForm value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.username )
        , ( 2, Protobuf.Encode.string value.password )
        , ( 3, Protobuf.Encode.string value.recaptcha )
        ]


{-| `LoginForm` message


-}
type alias LoginForm =
    { username : String, password : String, recaptcha : String }


{-| Default for ForgotPasswordConfirmForm. Should only be used for 'required' decoders as an initial value.


-}
defaultForgotPasswordConfirmForm : ForgotPasswordConfirmForm
defaultForgotPasswordConfirmForm =
    { recaptcha = "", username = "", token = "", password = "" }


{-| Decode a `ForgotPasswordConfirmForm` from Bytes


-}
decodeForgotPasswordConfirmForm : Protobuf.Decode.Decoder ForgotPasswordConfirmForm
decodeForgotPasswordConfirmForm =
    Protobuf.Decode.message
        defaultForgotPasswordConfirmForm
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | recaptcha = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | username = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | token = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | password = a })
        ]


{-| Encode a `ForgotPasswordConfirmForm` to Bytes


-}
encodeForgotPasswordConfirmForm : ForgotPasswordConfirmForm -> Protobuf.Encode.Encoder
encodeForgotPasswordConfirmForm value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.recaptcha )
        , ( 2, Protobuf.Encode.string value.username )
        , ( 3, Protobuf.Encode.string value.token )
        , ( 4, Protobuf.Encode.string value.password )
        ]


{-| `ForgotPasswordConfirmForm` message


-}
type alias ForgotPasswordConfirmForm =
    { recaptcha : String, username : String, token : String, password : String }


{-| Default for ForgotPasswordForm. Should only be used for 'required' decoders as an initial value.


-}
defaultForgotPasswordForm : ForgotPasswordForm
defaultForgotPasswordForm =
    { recaptcha = "", username = "" }


{-| Decode a `ForgotPasswordForm` from Bytes


-}
decodeForgotPasswordForm : Protobuf.Decode.Decoder ForgotPasswordForm
decodeForgotPasswordForm =
    Protobuf.Decode.message
        defaultForgotPasswordForm
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | recaptcha = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | username = a })
        ]


{-| Encode a `ForgotPasswordForm` to Bytes


-}
encodeForgotPasswordForm : ForgotPasswordForm -> Protobuf.Encode.Encoder
encodeForgotPasswordForm value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.recaptcha ), ( 2, Protobuf.Encode.string value.username ) ]


{-| `ForgotPasswordForm` message


-}
type alias ForgotPasswordForm =
    { recaptcha : String, username : String }


{-| Default for ContactForm. Should only be used for 'required' decoders as an initial value.


-}
defaultContactForm : ContactForm
defaultContactForm =
    { email = "", message = "", name = "", recaptcha = "" }


{-| Decode a `ContactForm` from Bytes


-}
decodeContactForm : Protobuf.Decode.Decoder ContactForm
decodeContactForm =
    Protobuf.Decode.message
        defaultContactForm
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | email = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | message = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | recaptcha = a })
        ]


{-| Encode a `ContactForm` to Bytes


-}
encodeContactForm : ContactForm -> Protobuf.Encode.Encoder
encodeContactForm value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.email )
        , ( 2, Protobuf.Encode.string value.message )
        , ( 3, Protobuf.Encode.string value.name )
        , ( 4, Protobuf.Encode.string value.recaptcha )
        ]


{-| `ContactForm` message


-}
type alias ContactForm =
    { email : String, message : String, name : String, recaptcha : String }


{-| Default for Cart. Should only be used for 'required' decoders as an initial value.


-}
defaultCart : Cart
defaultCart =
    { items = [] }


{-| Decode a `Cart` from Bytes


-}
decodeCart : Protobuf.Decode.Decoder Cart
decodeCart =
    Protobuf.Decode.message defaultCart [ Protobuf.Decode.repeated 1 decodeCartItem .items (\a r -> { r | items = a }) ]


{-| Encode a `Cart` to Bytes


-}
encodeCart : Cart -> Protobuf.Encode.Encoder
encodeCart value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.list encodeCartItem value.items ) ]


{-| `Cart` message


-}
type alias Cart =
    { items : List CartItem }


{-| Default for CartItem. Should only be used for 'required' decoders as an initial value.


-}
defaultCartItem : CartItem
defaultCartItem =
    { timestamp = "", domain = "" }


{-| Decode a `CartItem` from Bytes


-}
decodeCartItem : Protobuf.Decode.Decoder CartItem
decodeCartItem =
    Protobuf.Decode.message
        defaultCartItem
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | timestamp = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | domain = a })
        ]


{-| Encode a `CartItem` to Bytes


-}
encodeCartItem : CartItem -> Protobuf.Encode.Encoder
encodeCartItem value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.timestamp ), ( 2, Protobuf.Encode.string value.domain ) ]


{-| `CartItem` message


-}
type alias CartItem =
    { timestamp : String, domain : String }


{-| Default for User. Should only be used for 'required' decoders as an initial value.


-}
defaultUser : User
defaultUser =
    { token = "", subscribed = False, admin = False }


{-| Decode a `User` from Bytes


-}
decodeUser : Protobuf.Decode.Decoder User
decodeUser =
    Protobuf.Decode.message
        defaultUser
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | token = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.bool (\a r -> { r | subscribed = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.bool (\a r -> { r | admin = a })
        ]


{-| Encode a `User` to Bytes


-}
encodeUser : User -> Protobuf.Encode.Encoder
encodeUser value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.token )
        , ( 2, Protobuf.Encode.bool value.subscribed )
        , ( 3, Protobuf.Encode.bool value.admin )
        ]


{-| `User` message


-}
type alias User =
    { token : String, subscribed : Bool, admin : Bool }


{-| Default for Restore. Should only be used for 'required' decoders as an initial value.


-}
defaultRestore : Restore
defaultRestore =
    { id = "", timestamp = "", domain = "", status = "", s3Url = "", transactDate = "", username = "", email = "" }


{-| Decode a `Restore` from Bytes


-}
decodeRestore : Protobuf.Decode.Decoder Restore
decodeRestore =
    Protobuf.Decode.message
        defaultRestore
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | id = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | timestamp = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | domain = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | status = a })
        , Protobuf.Decode.optional 5 Protobuf.Decode.string (\a r -> { r | s3Url = a })
        , Protobuf.Decode.optional 6 Protobuf.Decode.string (\a r -> { r | transactDate = a })
        , Protobuf.Decode.optional 7 Protobuf.Decode.string (\a r -> { r | username = a })
        , Protobuf.Decode.optional 8 Protobuf.Decode.string (\a r -> { r | email = a })
        ]


{-| Encode a `Restore` to Bytes


-}
encodeRestore : Restore -> Protobuf.Encode.Encoder
encodeRestore value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.id )
        , ( 2, Protobuf.Encode.string value.timestamp )
        , ( 3, Protobuf.Encode.string value.domain )
        , ( 4, Protobuf.Encode.string value.status )
        , ( 5, Protobuf.Encode.string value.s3Url )
        , ( 6, Protobuf.Encode.string value.transactDate )
        , ( 7, Protobuf.Encode.string value.username )
        , ( 8, Protobuf.Encode.string value.email )
        ]


{-| `Restore` message


-}
type alias Restore =
    { id : String
    , timestamp : String
    , domain : String
    , status : String
    , s3Url : String
    , transactDate : String
    , username : String
    , email : String
    }


{-| Default for Receipt. Should only be used for 'required' decoders as an initial value.


-}
defaultReceipt : Receipt
defaultReceipt =
    { id = "", url = "", date = "", amount = "" }


{-| Decode a `Receipt` from Bytes


-}
decodeReceipt : Protobuf.Decode.Decoder Receipt
decodeReceipt =
    Protobuf.Decode.message
        defaultReceipt
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | id = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | url = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | date = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | amount = a })
        ]


{-| Encode a `Receipt` to Bytes


-}
encodeReceipt : Receipt -> Protobuf.Encode.Encoder
encodeReceipt value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.id )
        , ( 2, Protobuf.Encode.string value.url )
        , ( 3, Protobuf.Encode.string value.date )
        , ( 4, Protobuf.Encode.string value.amount )
        ]


{-| `Receipt` message


-}
type alias Receipt =
    { id : String, url : String, date : String, amount : String }


{-| Default for Data. Should only be used for 'required' decoders as an initial value.


-}
defaultData : Data
defaultData =
    { user = Nothing, id = "", url = "", info = "", receipts = [], restores = [], restore = Nothing }


{-| Decode a `Data` from Bytes


-}
decodeData : Protobuf.Decode.Decoder Data
decodeData =
    Protobuf.Decode.message
        defaultData
        [ Protobuf.Decode.optional 1 (Protobuf.Decode.map Just decodeUser) (\a r -> { r | user = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | id = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | url = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | info = a })
        , Protobuf.Decode.repeated 5 decodeReceipt .receipts (\a r -> { r | receipts = a })
        , Protobuf.Decode.repeated 6 decodeRestore .restores (\a r -> { r | restores = a })
        , Protobuf.Decode.optional 7 (Protobuf.Decode.map Just decodeRestore) (\a r -> { r | restore = a })
        ]


{-| Encode a `Data` to Bytes


-}
encodeData : Data -> Protobuf.Encode.Encoder
encodeData value =
    Protobuf.Encode.message
        [ ( 1, (Maybe.map encodeUser >> Maybe.withDefault Protobuf.Encode.none) value.user )
        , ( 2, Protobuf.Encode.string value.id )
        , ( 3, Protobuf.Encode.string value.url )
        , ( 4, Protobuf.Encode.string value.info )
        , ( 5, Protobuf.Encode.list encodeReceipt value.receipts )
        , ( 6, Protobuf.Encode.list encodeRestore value.restores )
        , ( 7, (Maybe.map encodeRestore >> Maybe.withDefault Protobuf.Encode.none) value.restore )
        ]


{-| `Data` message


-}
type alias Data =
    { user : Maybe User
    , id : String
    , url : String
    , info : String
    , receipts : List Receipt
    , restores : List Restore
    , restore : Maybe Restore
    }


{-| Default for Response. Should only be used for 'required' decoders as an initial value.


-}
defaultResponse : Response
defaultResponse =
    { error = "", status = Status_SUCCESS, data = Nothing }


{-| Decode a `Response` from Bytes


-}
decodeResponse : Protobuf.Decode.Decoder Response
decodeResponse =
    Protobuf.Decode.message
        defaultResponse
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | error = a })
        , Protobuf.Decode.optional 2 decodeStatus (\a r -> { r | status = a })
        , Protobuf.Decode.optional 3 (Protobuf.Decode.map Just decodeData) (\a r -> { r | data = a })
        ]


{-| Encode a `Response` to Bytes


-}
encodeResponse : Response -> Protobuf.Encode.Encoder
encodeResponse value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.error )
        , ( 2, encodeStatus value.status )
        , ( 3, (Maybe.map encodeData >> Maybe.withDefault Protobuf.Encode.none) value.data )
        ]


{-| `Response` message


-}
type alias Response =
    { error : String, status : Status, data : Maybe Data }


{-| Encode a `Status` to Bytes


-}
encodeStatus : Status -> Protobuf.Encode.Encoder
encodeStatus value =
    Protobuf.Encode.int32 <|
        case value of
            Status_SUCCESS ->
                0

            Status_FAILED ->
                1

            StatusUnrecognized_ i ->
                i


{-| Decode a `Status` from Bytes


-}
decodeStatus : Protobuf.Decode.Decoder Status
decodeStatus =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        Status_SUCCESS

                    1 ->
                        Status_FAILED

                    _ ->
                        StatusUnrecognized_ i
            )


{-| `Status` enumeration


-}
type Status
    = Status_SUCCESS
    | Status_FAILED
    | StatusUnrecognized_ Int
